# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 17.x]

    name: NodeJS ${{ matrix.node-version }} sample
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up NodeJS
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
    
  publish-test-results:
      # - name: Upload coverage to Codecov
      #     uses: codecov/codecov-action@v2
      #     with:
      #       token: ${{ secrets.CODECOV_TOKEN }}
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: Unit Test Results
        files: "coverage/*.xml"
      
          
  